# Generated by Django 2.1.4 on 2019-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walpapir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='handle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
