# Generated by Django 2.0.1 on 2018-12-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walpapir', '0002_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pointCount',
            field=models.IntegerField(default=0),
        ),
    ]
