# Generated by Django 2.1.5 on 2019-04-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walpapir', '0002_auto_20190419_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='aaa', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='aaa', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(default='profile_image\\180x120.jpeg', upload_to='profile_image'),
        ),
    ]
