# Generated by Django 2.1.5 on 2019-01-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walpapir', '0002_auto_20190111_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
