# Generated by Django 2.1.5 on 2019-02-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walpapir', '0005_auto_20190128_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='self_introduction',
            new_name='bio',
        ),
    ]
