# Generated by Django 2.1.5 on 2019-02-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walpapir', '0007_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='bio'),
        ),
    ]
