# Generated by Django 2.1.5 on 2019-02-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walpapir', '0008_auto_20190203_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='bio', max_length=300),
        ),
    ]
